2024-09-13 04:34:00,468 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:38:00,558 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:42:00,679 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:46:00,739 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:50:00,835 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:54:00,923 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:58:01,035 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:02:00,150 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:06:00,288 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:10:00,552 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:14:00,729 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:18:00,762 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:22:01,095 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:26:00,391 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:30:00,852 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:34:00,958 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:38:00,447 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:42:00,557 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:46:00,145 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:50:00,568 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:11:04,088 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:14:00,199 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:18:00,245 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:22:00,371 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
