2024-09-13 04:34:00,468 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:38:00,558 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:42:00,679 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:46:00,739 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:50:00,835 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:54:00,923 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 04:58:01,035 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:02:00,150 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:06:00,288 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:10:00,552 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:14:00,729 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:18:00,762 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:22:01,095 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:26:00,391 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:30:00,852 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:34:00,958 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:38:00,447 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:42:00,557 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:46:00,145 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 05:50:00,568 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:11:04,088 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:14:00,199 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:18:00,245 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-13 06:22:00,371 ERROR scheduler Exception in Enqueue Events for Site airplane_mode
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 106, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 150, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 163, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 846, in get_single_value
    ).run()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/query_builder/utils.py", line 84, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 213, in sql
    self.connect()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/database.py", line 118, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 107, in get_connection
    conn = self._get_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 113, in _get_connection
    return self.create_connection()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/database/mariadb/database.py", line 116, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_eba4954b699568f5'@'localhost' (using password: YES)")
2024-09-14 18:26:00,727 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for airplane_mode.com
2024-09-14 18:26:00,767 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for airplane_mode.com
2024-09-22 01:14:00,992 ERROR scheduler Exception in Enqueue Events for Site airplane_mode.com
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 1080, in get_connection
    if connection.can_read():
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 490, in can_read
    return self._parser.can_read(timeout)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 81, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/_parsers/hiredis.py", line 92, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 109, in enqueue_events_for_site
    enqueue_events()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 129, in enqueue_events
    if job_type.enqueue():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 70, in enqueue
    if not self.is_job_in_queue():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 92, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 596, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 601, in get_job_status
    if job := get_job(job_id):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 607, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/rq/job.py", line 991, in refresh
    data = self.connection.hgetall(self.key)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/commands/core.py", line 4966, in hgetall
    return self.execute_command("HGETALL", name)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 1084, in get_connection
    connection.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-09-22 01:18:00,059 ERROR scheduler Exception in Enqueue Events for Site airplane_mode.com
Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 277, in connect
    sock = self.retry.call_with_retry(
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 278, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 639, in _connect
    raise err
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 627, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 109, in enqueue_events_for_site
    enqueue_events()
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/scheduler.py", line 129, in enqueue_events
    if job_type.enqueue():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 70, in enqueue
    if not self.is_job_in_queue():
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 92, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 596, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 601, in get_job_status
    if job := get_job(job_id):
  File "/home/yuga/Airplane_Mode/apps/frappe/frappe/utils/background_jobs.py", line 607, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/rq/job.py", line 591, in fetch
    job.refresh()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/rq/job.py", line 991, in refresh
    data = self.connection.hgetall(self.key)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/commands/core.py", line 4966, in hgetall
    return self.execute_command("HGETALL", name)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/client.py", line 545, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 1074, in get_connection
    connection.connect()
  File "/home/yuga/Airplane_Mode/env/lib/python3.10/site-packages/redis/connection.py", line 283, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2024-10-01 00:30:00,415 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,204 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,228 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,251 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,265 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,272 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for airplane_mode.com
2024-10-18 23:18:00,287 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for airplane_mode.com
